AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lambda-ec2-S3-creation
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::XXXXXXXXXX:role/MyLambdaExecutionRole
      Code:
        S3Bucket: sanjay-lambda-python-code
        S3Key: sanjay-lambda-code.zip
      Runtime: python3.9
      Timeout: 60

  MyEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: LambdaCronTrigger
      ScheduleExpression: cron(0 9 ? * 2 *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt MyLambdaFunction.Arn
          Id: CronTrigger
          Input: '{}'

  MyLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MyLambdaFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt MyEventRule.Arn


######Assumptions
#1. Roles and acess required for Cloud Formation Template are already in place.
#2. Source code is pushed by Jenkins pipeline to mentioned S3 buckte.
